In [2]:
pip install numpy


[notice] A new release of pip is available: 25.1.1 -> 26.0
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.


In [3]:
import numpy as np

# create array using numpy
# create a 1D array
arr1 = np.array([1, 2, 3, 4, 5])
print(arr1)
print(type(arr1))
print(arr1.shape)


[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [7]:
# 1d array
arr2 = np.array([1, 2, 3, 4, 5])
arr2.reshape(1, 5) #1 Row and 5 columns


array([[1, 2, 3, 4, 5]])

In [8]:
# 2d array
arr3 = np.array([[1, 2, 3,4 ,5 ], [2, 3, 4, 5, 6]])
arr3.shape
print(arr3)
print(arr3.shape)

[[1 2 3 4 5]
 [2 3 4 5 6]]
(2, 5)


In [12]:
# np.arange(0, 11, 2)
np.arange(0, 11, 2).reshape(6,1)

array([[ 0],
       [ 2],
       [ 4],
       [ 6],
       [ 8],
       [10]])

In [13]:
np.ones((3, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [14]:
# Identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [15]:
# Attributes of numpy array

arr = np.array([[1, 2, 3], [4, 5, 6]])
print("Array: \n", arr)
print("Shape:", arr.shape) # (2, 3)
print("Number of dimension", arr.ndim) # 2
print("Size (number of elements):", arr.size) # 6
print("Data type:", arr.dtype) # int64
print("Item size (in bytes):", arr.itemsize) #8

Array: 
 [[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Number of dimension 2
Size (number of elements): 6
Data type: int64
Item size (in bytes): 8


In [16]:
# Numpy Vectorized Operations:
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([10, 20, 30, 40, 50])

# Element Wise addition
print("Addition:", arr1 + arr2)

# Element Wise substraction
print("Substraction:", arr1 - arr2)

# Element Wise multiplication
print("Multiplication:", arr1 * arr2)


# Element Wise division
print("Division:", arr1 / arr2)

Addition: [11 22 33 44 55]
Substraction: [ -9 -18 -27 -36 -45]
Multiplication: [ 10  40  90 160 250]
Division: [0.1 0.1 0.1 0.1 0.1]


In [17]:
# Universal Function

arr = np.array([2, 3, 4, 5, 6])

# Square root
print(np.sqrt(arr))

# Exponential
print(np.exp(arr))

# Sine
print(np.sin(arr))

# natural log
print(np.log(arr))

[1.41421356 1.73205081 2.         2.23606798 2.44948974]
[  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]
[ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
[0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


In [18]:
# array slicing and Indexing

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print("Array: \n", arr)

Array: 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [19]:
arr[0][0]
print(arr[0:2, 2:])


[[3 4]
 [7 8]]


In [20]:
arr[1:]

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [21]:
print(arr[1:, 1: 3])

[[ 6  7]
 [10 11]]


In [22]:
arr[1:, 2:]

array([[ 7,  8],
       [11, 12]])

In [23]:
# Modify array elements
arr[0, 0] = 100
print(arr)

[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


In [24]:
arr[1:] = 100
print(arr)

[[100   2   3   4]
 [100 100 100 100]
 [100 100 100 100]]


In [26]:
# Stattistical concepts -- Normalization
# to have a mean of 0 and standard deviation of 1
data = np.array([1, 2, 3, 4, 5])

# calculatee the mean and standard deviation
mean = np.mean(data)
std_dev = np.std(data)

# Normalize the data
normalized_data = (data - mean) / std_dev
print("Normalized data: ", normalized_data)

# Variance
variance = np.var(data)
print("Variance:", variance) 

# Output:
# Normalized data: [-1.26491106 -0.63245553 0. 0.63245553 1.26491106]

Normalized data:  [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]
Variance: 2.0


In [28]:
# Logical operation:-
data = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
data[(data >= 5) & (data <= 8)]


array([5, 6, 7, 8])